name: Parser Tests

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.4'
    - name: Compile
      run: javac parser/*.java tests/expression/*.java tests/parser/*.java
    
    - name: Run ParserTest Easy
      run: java -ea tests/parser/ParserTest easy
    
    - name: Run ParserShiftsTest Easy
      run: java -ea tests/parser/ParserShiftsTest easy
    
    - name: Run ParserAbsSquareTest Easy
      run: java -ea tests/parser/ParserAbsSquareTest easy
    
    - name: Run ParserReverseDigitsTest Easy
      run: java -ea tests/parser/ParserReverseDigitsTest easy
    
    - name: Run ParserTest Hard
      run: java -ea tests/parser/ParserTest hard
    
    - name: Run ParserShiftsTest Hard
      run: java -ea tests/parser/ParserShiftsTest hard
    
    - name: Run ParserAbsSquareTest Hard
      run: java -ea tests/parser/ParserAbsSquareTest hard
    
    - name: Run ParserReverseDigitsTest Hard
      run: java -ea tests/parser/ParserReverseDigitsTest hard

      
